### ISSUE TITLE
Plotting horizontal images in x,y space

### ISSUE THREAD

**Issue by kshedstrom** [ESMG/PyCNAL#5]
I tried @adcroft 's gplot.py on the supercritical problem and it draws things in i,j space, not curvilinear x,y space. Do we have an example of plotting in x,y space?

**Comment by adcroft** [comment]
Options -sg for supergrid or -os for coordinate provided by diag_table (add geolon and geolat to the diag_table).

(Clumsy fingers closed issue by accident)

**Comment by kshedstrom** [comment]
```
usage: gplot.py [-h] [-cm COLORMAP] [--clim MIN MAX] [--ignore IGNORE]
                [--ignorelt IGNORELT] [--ignoregt IGNOREGT] [--scale SCALE]
                [--offset OFFSET] [--log10] [-sg SUPERGRID] [-os OCEANSTATIC]
                [-IJ] [-e ELEVATION] [--animate] [-o OUTPUT] [-r RESOLUTION]
                [-ar WIDTH HEIGHT] [--stats] [--list] [-d]
                FILE[,VARIABLE[,SLICE1[,SLICE2[...]]]]
```
This isn't how to use -sg obviously, will try the diag_table next.
```
gplot.py -sg INPUT/ocean_hgrid.nc  prog.nc,u,3
Traceback (most recent call last):
  File "/import/c1/AKWATERS/kate/ESMG/pyGVtools/gplot.py", line 944, in <module>
    if __name__ == '__main__': parseCommandLine()
  File "/import/c1/AKWATERS/kate/ESMG/pyGVtools/gplot.py", line 118, in parseCommandLine
    createUI(optCmdLineArgs.file_var_slice, optCmdLineArgs)
  File "/import/c1/AKWATERS/kate/ESMG/pyGVtools/gplot.py", line 178, in createUI
    render(var, args, elevation=eVar)
  File "/import/c1/AKWATERS/kate/ESMG/pyGVtools/gplot.py", line 246, in render
    xCoord, xLims = readSGvar(args.supergrid, 'x', var.dims)
  File "/import/c1/AKWATERS/kate/ESMG/pyGVtools/gplot.py", line 859, in readSGvar
    xSlice1 = slice(xVarDim.slice1.start*2, xVarDim.slice1.stop*2+1, 2)
AttributeError: 'NoneType' object has no attribute 'slice1'
```

**Comment by kshedstrom** [comment]
It wants "geolon_c", but still no luck:
```
gplot.py -os prog.nc prog.nc,u,3
Traceback (most recent call last):
  File "/import/c1/AKWATERS/kate/ESMG/pyGVtools/gplot.py", line 944, in <module>
    if __name__ == '__main__': parseCommandLine()
  File "/import/c1/AKWATERS/kate/ESMG/pyGVtools/gplot.py", line 118, in parseCommandLine
    createUI(optCmdLineArgs.file_var_slice, optCmdLineArgs)
  File "/import/c1/AKWATERS/kate/ESMG/pyGVtools/gplot.py", line 178, in createUI
    render(var, args, elevation=eVar)
  File "/import/c1/AKWATERS/kate/ESMG/pyGVtools/gplot.py", line 242, in render
    xCoord, xLims = readOSvar(args.oceanstatic, 'geolon_c', var.dims)
  File "/import/c1/AKWATERS/kate/ESMG/pyGVtools/gplot.py", line 899, in readOSvar
    ySlice1 = slice(yVarDim.slice1.start, yVarDim.slice1.stop)
AttributeError: 'NoneType' object has no attribute 'slice1'
```

**Comment by kshedstrom** [comment]
Maybe I should add that I'm using my python3 fork...
